### ISSUE TITLE
Size of text rectangles not calculated correctly

### ISSUE THREAD

**Issue by Ebiroll** [Dax89/QHexView#19]
![image](https://user-images.githubusercontent.com/8543484/56355419-87c15200-61d6-11e9-8d03-af438fc71845.png)
As you can see from image the width of the texts are not correct.

I just try to set the document from a file.
    QHexView *pcntwgt = dynamic_cast<QHexView *>(centralWidget());
    QHexDocument* document = QHexDocument::fromFile<QMemoryBuffer>(fileName);
    pcntwgt->setDocument(document);

**Comment by Ebiroll** [comment]
OK, So maybe it is a font issue on Linux.
I solved the issue with this patch.

QHexView::QHexView(QWidget *parent) : QAbstractScrollArea(parent), m_document(NULL), m_renderer(NULL), m_readonly(false)
{
    //this->setFont(QFontDatabase::systemFont(QFontDatabase::FixedFont));
    QFont font("Monospace");
    font.setStyleHint(QFont::TypeWriter);
    this->setFont(font);

**Comment by Dax89** [comment]
It looks like a Qt bug:
* https://forum.qt.io/topic/95826/qfontdatabase-doesn-t-give-me-a-fixed-font-lubuntu-18-10/4
* https://bugreports.qt.io/browse/QTBUG-54623

The workaround is more or less the one posted by you

From qt.io:
```
if (fixedFont.fixedPitch() == false) { // workaround for QTBUG-54623
   fixedFont.setFamily("monospace");
}
```

I can add this workaround to the widget...thanks for reporting!

**Comment by Ebiroll** [comment]
OK. It looks like it fixed the Issue. 
It would be good to have some simple examples for this widget.
i.e. I am trying to set the cursor to an offset.

	QHexView *pcntwgt = dynamic_cast<QHexView *>(centralWidget());
        QHexCursor* cur = pcntwgt->document()->cursor();
        int reminder=offset%16;
        cur->moveTo(offset/16,reminder,0);

Does not work. :-( Maybe  some kind of repaint() is required....

**Comment by Ebiroll** [comment]
Actually,
I added an   emit positionChanged(); in the QHexCursor::moveTo function, then it worked as I expected.

    void QHexCursor::moveTo(int line, int column, int nibbleindex)
    {
     ...
        emit positionChanged();
    }
