### ISSUE TITLE
memory mapped file or similar windowing support

### ISSUE THREAD

**Issue by Lewiscowles1986** [Dax89/QHexView#20]
Does this view support separation of scrollbar from contents?

I'm thinking of large file support here. Has this been tested for displaying large files, or with scroll-handlers for loading fixed-size buffers

https://github.com/Dax89/QHexView/tree/master/document/buffer looks promising, but as there are no tests I thought it might be easier to ask

**Comment by Dax89** [comment]
The widget will paint only the visible area according to the scrollbar's position, so it's pretty fast.

Editing a large file is a bit tricky, you need to inherit from this class: https://github.com/Dax89/QHexView/blob/master/document/buffer/qhexbuffer.h, and implement the abstract methods with some large file support algorithm (gap buffer, piece chains etc).

**Comment by Lewiscowles1986** [comment]
I'll close this. 

> Editing a large file is a bit tricky, you need to inherit from this class: https://github.com/Dax89/QHexView/blob/master/document/buffer/qhexbuffer.h, and implement the abstract methods with some large file handling algorithm (gap buffer, piece chains etc).

exactly what I was asking I think, so this is presentation and implementing that would be what controlled implementation specifics :+1: 

Very cool library btw
