### ISSUE TITLE
Handling multiple metadata objects on the same line

### ISSUE THREAD

**Issue by sykhro** [Dax89/QHexView#24]
When hovering a metadata element, the tooltip displays the string from all the metadata inserted in that line. Is this the expected behaviour?
![met](https://user-images.githubusercontent.com/8491400/59145768-beeafd00-89e8-11e9-8388-d8424da261b9.png)

**Comment by Dax89** [comment]
Mmmh, it looks like a bug.

**Comment by sykhro** [comment]
Well, by looking at the code it seems like elements are all merged in a single tooltip
https://github.com/Dax89/QHexView/blob/cf58941cb8e545eda6b964f854aae0bb353d2935/document/qhexmetadata.cpp#L18-L31
https://github.com/Dax89/QHexView/blob/4524ca368221c2883a0743d77412fbcfe6fe457b/qhexview.cpp#L81-L84
I got around this with a silly hack downstream for now

**Comment by sykhro** [comment]
fixed by fca3521
