### ISSUE TITLE
Fractional QFont width on a Pi

### ISSUE THREAD

**Issue by audetto** [Dax89/QHexView#48]
On a Pi 400 with default software I get a Monospaced ``QFont`` which has an integer **point** size, but a fractional **pixel** size = ``9.59375``.

This means that all operations where the width of one cell is multiplied by N, accumulate an error and after 16 or 32 (* 3) characters, when I select a char the rounding is such that it selects something 2 or 3 characters before.

The solution is possible and would imply using ``QFontMetricsF`` and ``qreal``, plus some rounding. Makes code a bit more complicated, but...

Do you have any opinion?

**Comment by audetto** [comment]
After further analysis, the size are fractional in other case (Ubuntu on my PC) = ``9.015625``

The only difference is that with this number one needs more character to get an error that accumulates to become visible, while on Pi, 9.5 is very unfortunate.

**Comment by Dax89** [comment]
Yes it's a good idea to use `QFontMetricsF`, in other projects I always had this problem with the classic `QFontMetrics`.

I see if I can find the time to change the code in order to use the "floating pointed" version

**Comment by audetto** [comment]
https://github.com/Dax89/QHexView/pull/50

**Comment by audetto** [comment]
fixed in https://github.com/Dax89/QHexView/pull/50
