### ISSUE TITLE
support change font size using setFont(...)

### ISSUE THREAD

**Issue by shinespeciall** [Dax89/QHexView#55]
currently using this can only change the font size but the rendered lines' position in the widget are fixed
> hexview->setFont(QFont("Timers", 8, QFont::Bold));
![image](https://user-images.githubusercontent.com/28697038/117842768-d4da5a00-b2b0-11eb-80f1-64f27938adfd.png)

**Comment by Dax89** [comment]
I have made some changes, let me know if it works!

**Comment by shinespeciall** [comment]
it works, thanks for the quick fix !
![image](https://user-images.githubusercontent.com/28697038/119212108-e7426800-bae8-11eb-942f-e134a59e8e76.png)

**Comment by aerosoul94** [comment]
@shinespeciall How did you make 00 and FF bytes the same color?

**Comment by shinespeciall** [comment]
i think that is cused by the phantomstyle theme i am using or the palette settings for the whole project:
phantomstyle: https://github.com/randrew/phantomstyle/tree/master
custom color in the project: https://github.com/wario-land/WL4Editor/blob/chunk_editor/Themes.h
reset the project's UI palette: https://github.com/wario-land/WL4Editor/blob/chunk_editor/WL4EditorWindow.cpp#L41

**Comment by Dax89** [comment]
00 and FF bytes are changed here:

https://github.com/Dax89/QHexView/blob/master/document/qhexrenderer.cpp#L218
