### ISSUE TITLE
Renderer does not work well with widget’s width

### ISSUE THREAD

**Issue by T-640** [Dax89/QHexView#57]
Hello!

If Widget’s width is larger than renderer’s painting area it simply paints white after the ASCII column. This does not look good. Renderer should paint over the entire widget’s area. I see two possible solutions:

1) Stretch and automatically increase font as widget grows larger;

2) Set fixed width on widget, give control over how it resizes to renderer instead. Widget’s size could then be set programmatically by some external event, say font change, for example. Something like this could be called each time widget needs to resize: hex_view->setMaximumWidth (m_renderer->documentWidth())

**Comment by audetto** [comment]
Hi

could you please give some example of this.

Which version of the code are you using?

**Comment by T-640** [comment]
I was using the latest version (as of the date of opening this issue). This is what I am talking about:

![Hex view visual issue](https://user-images.githubusercontent.com/71297562/119267069-e1867880-bbf5-11eb-8b3b-36a8b171838d.png)

**Comment by audetto** [comment]
This is what VSCode does.

![2021-05-23-180552_1920x1080_scrot](https://user-images.githubusercontent.com/212523/119269861-bb5ed980-bbf1-11eb-95dd-ea768404fb54.png)

**Comment by T-640** [comment]
Looks odd as well from my point of view. Although it would seem that every other hex editor does it this way. Just had a look at HxD (hex editor for Windows) and there it is this same gap between data and scroll bar. I guess this is just my personal preference then.

But still, don’t you find that huge gap odd? Wouldn’t it be more aesthetically pleasing for the scroll bar to always be next to the ASCII column no matter what, without these big gaps in-between?
