### ISSUE TITLE
Incorrect cursor selection rendering in ASCII area

### ISSUE THREAD

**Issue by T-640** [Dax89/QHexView#63]
When the last byte at the end of a line of the hex area is selected, the corresponding character in ASCII area is not. Take a look at this screenshot, the last zero in ASCII area is not highlighted, but is supposed to be:

![Selection issue 1](https://user-images.githubusercontent.com/71297562/121819784-b5f82a80-cc97-11eb-9003-c389dc2b8076.png)

The culprit is QHexRenderer::applySelection. 1 is subtracted in two places, resulting in this behaviour.

https://github.com/Dax89/QHexView/blob/4d06da87e7e9202d1d760afaee6f4a4b297612fc/document/qhexrenderer.cpp#L267-L295

I experimented by removing these “-1” parts and it fixed the issue, but introduced a new one. Now in hex area a redundant piece is selected (notice how selection is extended past the last number 30 compared to the previous screenshot):

![Selection issue 2](https://user-images.githubusercontent.com/71297562/121819819-e2ac4200-cc97-11eb-955c-699bff104fe4.png)

**Comment by T-640** [comment]
> The hex selection is always 3 char wide as each char is 2 nibbles and a space.

 I see, indeed, this is not a bug but simply how hex area is designed to work.

Nevertheless, aesthetically, I think, it looks better when these two “empty” characters which separate Hex from Ascii areas are not touched by the selection.

Maybe @Dax89 put this “-1” on purpose to deal with this particular case at the end of the line, where only 2 characters instead of 3 need to be selected, forgetting that it messes up the Ascii area?

I see that applySelection() is called in 2 places, by drawHex() and drawAscii(). Perhaps “-1” could be reintroduced as some optional argument, used from the drawHex() call only?

**Comment by audetto** [comment]
What do you want to happen when the selection spans multiple Hex lines?
Do you want the last (empty) character of a line to appear selected or not?

If you don't want it to be selected, then one must change this too https://github.com/Dax89/QHexView/blob/05d1cf758967b4cdb21c98b79a7fe7cf7949cd39/document/qhexrenderer.cpp#L286 and not use `QTextCursor::EndOfLine` but add a `-1` there too.

Is this the rule you have in mind? only ever select the space if in between selected characters and never at the end of a line.

**Comment by T-640** [comment]
> ... only ever select the space if in between selected characters and never at the end of a line.
> 
> ![image](https://user-images.githubusercontent.com/212523/143689784-b31ab708-4dc6-43f1-85ae-7c45a41bd10a.png)
> 
> this is VSCode.

Pretty much this, and the screenshot illustrates it too. I think it looks better this way.

**Comment by audetto** [comment]
What about this?

![image](https://user-images.githubusercontent.com/212523/143783531-5d672efa-b221-4d5e-bcf4-77f35de3727d.png)

I've updated the PR.

**Comment by T-640** [comment]
Perfect, thank you!

The only small thing I’d change is removing braces from here:

https://github.com/audetto/QHexView/blob/0b7ca06a77e17b3713477a877c3d1c5890ae3b5f/document/qhexrenderer.cpp#L289-L292

And while we’re at it, perhaps the factor argument to ```applySelection``` could be ```enum``` instead of ```int```?

```c++
enum Factor {Ascii = 1, Hex = 3}
```
So one could write ```if (factor == Hex)``` without the need to write the comment, and the function could be called this way instead ```applySelection (textcursor, line, Hex)```

**Comment by T-640** [comment]
I see that my previous small suggestion have made it to the code as well, the issue is now fully resolved, thanks!
