### ISSUE TITLE
QHexView does not support Qt5.7

### ISSUE THREAD

**Issue by neomissing** [Dax89/QHexView#69]
QByteArray::toHex(char separator) is supported as of Qt5.9, so earlier versions will not compile

**Comment by T-640** [comment]
There is actually at least one good reason to support older versions: they are licensed under LGPL version 2. Halfway through they changed it to version 3 which, as far as I understand, makes it nearly impossible to write commercial software for mobile phones and pretty much anything other than desktop computers, unless you pay them, of course.

And not that it matters that much, but these older versions support Windows XP and have pre-built binaries for x86 Linux. Plenty of old but still perfectly functioning hardware is still around.

**Comment by Dax89** [comment]
Afaik there is no problem to select an older version of Qt and keep compatibility with it.

I can try to keep backward compatibility with Qt 5.6 which is an LTS (even if it is unsupported).

**Comment by T-640** [comment]
Yea, this should be quite easy, ```QByteArray::toHex``` is the only function in QHexView that prevents compilation with older versions as far as I remember, and writing an equivalent for it should be pretty straightforward.

**Comment by Dax89** [comment]
I've removed toHex() call from the widget, check this branch: https://github.com/Dax89/QHexView/tree/5.0 I will move it to `master` this week.

If there is some other code that breaks backward compatibility, let me know

**Comment by T-640** [comment]
I have successfully compiled QHexView 5.0 with Qt 5.6.3.
